#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : adapt-parser
Version  : 0.3.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/36/a4/3ef82c754a8fb079a98d0adb66be1e3dc7a42d6faafdf1f106924a48c352/adapt-parser-0.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/36/a4/3ef82c754a8fb079a98d0adb66be1e3dc7a42d6faafdf1f106924a48c352/adapt-parser-0.3.0.tar.gz
Summary  : A text-to-intent parsing framework.
Group    : Development/Tools
License  : LGPL-3.0
Requires: adapt-parser-python = %{version}-%{release}
Requires: adapt-parser-python3 = %{version}-%{release}
Requires: pyee
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pyee
BuildRequires : six

%description
No detailed description available

%package python
Summary: python components for the adapt-parser package.
Group: Default
Requires: adapt-parser-python3 = %{version}-%{release}

%description python
python components for the adapt-parser package.


%package python3
Summary: python3 components for the adapt-parser package.
Group: Default
Requires: python3-core

%description python3
python3 components for the adapt-parser package.


%prep
%setup -q -n adapt-parser-0.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541264234
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
